subcracts from render
yabr87/purrfect-match-frontend pull request #148
Opened 2023-05-18 22:09 UTC by ViktorZvonar

Получилось: удаляет из рендера объявление, которое больш не фаворит

2023-05-18 22:50 UTC, mrSedmor requested changes
На странице sell. При удалении объявления из избранных по нажатию на сердечно оно удаляется из галереи.
В favorites adds. При удалении из избранных по нажатию в модальном окне объявление не удаляется

2023-05-19 07:44 UTC, closed without merging

2023-05-19 07:44 UTC, yabr87 commented
Виктор удали это

2023-05-19 10:42 UTC, ViktorZvonar reviewed
удаляю

2023-05-19 10:43 UTC, ViktorZvonar commented
оно вроде удалено