filterByAge done
yabr87/purrfect-match-frontend pull request #187
Opened 2023-05-20 14:50 UTC by ViktorZvonar

зробив фільт оголошеь за статтю. Викорситав getNotices на сторінці ноутісісПейдж. Там зробив стейт  const [sex, setSex] = useState(''). Поставив умову, якщо змінюється sex, то в setNotices записується відфільтрований список. 

Також змінив компонент checkbox - добавив обєкт event з ключем checked щоб відстежувати стан натиснутого чекбокса, щоб функція handleGenderChange в компоненті фільту спрацьовувала, тільки якщо чекбокс натиснутий

2023-05-20 16:12 UTC, mrSedmor commented
Фильтр должен не фильтровать полученные с бэкэнда объявления, а запрашивать.
То есть нужно делать вызов, например, GET /api/notices?category=sell&sex=male или GET /api/notices?title=cat&favorite=true&sex=female

2023-05-20 16:29 UTC, AlonaMaliarchyk reviewed
А можна змінити індекс на 9 в фейворіт та кругла кнопка? Бо він заважає випаду фільтрів(я фільтрам дала 10 індекс).Я в себе внесла зміни

2023-05-20 18:45 UTC, mrSedmor commented
Некорректное поведение когда вначале выбираем один пол, затем не снимая галочку другой пол, потом убираем первую галочку. Посмотри какие запросы отправляются на бэкэнд.

2023-05-20 18:48 UTC, mrSedmor commented
Если выбрано male и female либо ни одна из опций, запрос должен идти без sex. А если что-то одно выбрано, то с sex.

2023-05-20 19:36 UTC, annabramarova commented
там на твою страницу добавлена иконка редактирования питомца
и модалка к ней
когда будешь исправлять конфликт будь внимателен, т.к. нужны все изменения

2023-05-20 20:17 UTC, mrSedmor requested changes
Доделать и убедиться, что правильно работает.

2023-05-21 07:07 UTC, ViktorZvonar commented
> 

сделал

2023-05-21 07:21 UTC, mrSedmor approved these changes

2023-05-21 07:22 UTC, merged