Fix/ validation & styles
yabr87/purrfect-match-frontend pull request #198
Opened 2023-05-20 21:25 UTC by beligrous

відкоррегував адаптив та відступи, додав нотіфікацію при некорректному вводі

2023-05-20 21:45 UTC, mrSedmor requested changes
Вернуть маржины между карточками животных на десктопе.
Проверить и убрать выпадающие маржины. На десктопе такие есть.

2023-05-21 06:37 UTC, beligrous commented
исправил

2023-05-21 07:02 UTC, yabr87 approved these changes

2023-05-21 07:02 UTC, yabr87 approved these changes

2023-05-21 07:05 UTC, merged